/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*
 * MCO - PA8
 */
#include <stdint.h>

#define RCC_BASE_ADDR		0x40021000UL

// Clock configuration register
#define RCC_CFGR_REG_OFFSET	0x08UL
#define RCC_CFGR_REG_ADDR 	(RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)

// Clock to AHB2ENR
#define RCC_AHB2_ENR_OFFSET	0x4CUL
#define RCC_AHB2_ENR_ADDR	(RCC_BASE_ADDR + RCC_AHB2_ENR_OFFSET)

// GPIO
#define GPIOA_BASE_ADDR 	0x48000000UL

int main(void)
{

	uint32_t *pRccCfgrReg = (uint32_t*) RCC_CFGR_REG_ADDR;
	uint32_t *pRccAhb2Enr = (uint32_t*) RCC_AHB2_ENR_ADDR;

	// 1. Configure the RCC_CFGR
	// MCOSEL[3:0]: Microcontroller clock output. 0010: MSI clock selected.
	*pRccCfgrReg |= (0x2 << 24);
	// *pRccCfgrReg |= (0 << 28);

	// 2. configure PA8 to AF0 to set MC0 signal
	*pRccAhb2Enr |= (1 << 0);

	// 3. Configure GPIOA pin 8 as alternative function mode
	uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x00);
	*pGPIOAModeReg &= ~(0x3 << 16); // Clear
	*pGPIOAModeReg |= (0x2 << 16); // Set

	// 4. Configure alternative function register to set mode0 for PA8
	uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);
	*pGPIOAAltFunHighReg &= ~(0xf << 0);


	for(;;);
}
